### PR TITLE
added linked in and github icons with link to the respective profile,…

### PR DESCRIPTION
**Pull request by LorenzCronenberg**
- github and linked in icons with the link to the respective profile 
@Puresturheit do you have LinkedIn? I did not find you :( 
- I have put a link to the github repo to the icons in the footer 
- added the website slogan in the footer 
Screenshot 2020-12-03 at 16 22 41

### CODE REVIEW

**Comment by LorenzCronenberg** [comment]
I changed the position of the made with love text
What do you like more? 

Screenshot 2020-12-03 at 16 29 36

**Comment by LorenzCronenberg** [comment]
@melwers 
Screenshot 2020-12-03 at 16 33 19

**Comment by Gregkur** [comment]
Would add links to our githubs, but I like it!

**Comment by Gregkur** [comment]
https://www.linkedin.com/in/grzegorz-kurzajczyk-6abba4158/

**Pull request merged**
